<a href="https://colab.research.google.com/github/Rohita-G/rohita-gangishetty-700750412/blob/main/icp3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy
arr=numpy.array([9,8,7,6,5,4,3,2,1,11,0,20,13,14,15])
re=numpy.reshape(arr,(3,5))
print(re)
print(re.shape)
s=re.max(axis=1)
print(s)

[[ 9  8  7  6  5]
 [ 4  3  2  1 11]
 [ 0 20 13 14 15]]
(3, 5)
[ 9 11 20]


In [ ]:
import numpy as np
numpy_array = np.array([1, 2, 3, 4, -8, -10,11,4,6,3,1,6])
a=numpy_array.reshape(4,3)
print(a)
print("shape:",a.shape)
print("datatype:",a.dtype)
print("type",type(numpy_array))


[[  1   2   3]
 [  4  -8 -10]
 [ 11   4   6]
 [  3   1   6]]
shape: (4, 3)
datatype: int64
type <class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr=np.array([[0 ,1, 2],
             [3 ,4 ,5]])
print(arr)
print("sum of diagonal ele:",np.trace(arr))

[[0 1 2]
 [3 4 5]]
sum of diagonal ele: 4


In [ ]:
import numpy as np
arr=np.arange(10,71,2)
print("Array of all the even integers from 10 to 70",arr)
a=np.arange(11,70,2)
print("Array of all the odd integers from 10 to 70",a)
b=np.array([[0 ,1, 2],
             [3 ,4 ,5],
          [1,3,5]])
c=np.array([[1,2,3],
            [4,5,6],
           [6,4,3]])
print(np.add(b, c))
print(np.subtract(b, c))
print(np.multiply(b, c))
print(np.divide(b, c))
array =np.array( [[5.54, 3.38, 7.99],
 [3.54, 4.38, 6.99],
 [1.54, 2.39, 9.29]])
print("by col",np.sort(array,axis=0))
print("by row",np.sort(array,axis=1))




Array of all the even integers from 10 to 70 [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70]
Array of all the odd integers from 10 to 70 [11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57
 59 61 63 65 67 69]
[[ 1  3  5]
 [ 7  9 11]
 [ 7  7  8]]
[[-1 -1 -1]
 [-1 -1 -1]
 [-5 -1  2]]
[[ 0  2  6]
 [12 20 30]
 [ 6 12 15]]
[[0.         0.5        0.66666667]
 [0.75       0.8        0.83333333]
 [0.16666667 0.75       1.66666667]]
by col [[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]
by row [[3.38 5.54 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]


In [ ]:
import numpy as np

a=np.array( [[ 4, 2 ,np.nan, 1],
[11, 12, 14, 9],
 [5, np.nan, 1, np.nan]])
print(np.isnan(a))

[[False False  True False]
 [False False False False]
 [False  True False  True]]
